import argparse
import csv
import json
import shutil
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List


ENRICHER_VERSION = "coach_input_ai_judge_input_enricher_v0_7"


def project_root() -> Path:
    return Path(__file__).resolve().parents[2]


def rel(path: Path, root: Path) -> str:
    try:
        return str(path.relative_to(root)).replace("\\", "/")
    except ValueError:
        return str(path).replace("\\", "/")


def load_json(path: Path) -> Any:
    with path.open("r", encoding="utf-8-sig") as f:
        return json.load(f)


def write_json(path: Path, data: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="\n") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)


def compact(value: Any, limit_list: int = 12, limit_dict_keys: int = 50) -> Any:
    if isinstance(value, list):
        return [compact(x, limit_list, limit_dict_keys) for x in value[:limit_list]]
    if isinstance(value, dict):
        out = {}
        for i, (k, v) in enumerate(value.items()):
            if i >= limit_dict_keys:
                out["_truncated_keys"] = len(value) - limit_dict_keys
                break
            out[k] = compact(v, limit_list, limit_dict_keys)
        return out
    return value


def insert_after(items: List[str], after_value: str, new_value: str) -> List[str]:
    if new_value in items:
        return items
    out = []
    inserted = False
    for item in items:
        out.append(item)
        if item == after_value:
            out.append(new_value)
            inserted = True
    if not inserted:
        out.append(new_value)
    return out


def enrich(args: argparse.Namespace) -> Dict[str, Any]:
    root = project_root()
    match_id = args.match_id
    player = args.player

    pkg_dir = root / "data" / "package" / match_id
    ai_dir = root / "data" / "ai" / match_id

    coach_input_current = pkg_dir / "coach_input_package_current.json"
    ai_input_current = ai_dir / "ai_coach_judge_input_current.json"

    if not coach_input_current.exists():
        raise FileNotFoundError(f"MISSING coach input package: {coach_input_current}")

    if not ai_input_current.exists():
        raise FileNotFoundError(f"MISSING ai coach judge input: {ai_input_current}")

    coach_input = load_json(coach_input_current)
    ai_input = load_json(ai_input_current)

    if coach_input.get("meta", {}).get("version") != "v0_6":
        raise ValueError(f"Expected coach_input v0_6 before v0_7 enrichment, got {coach_input.get('meta', {}).get('version')}")

    backup_path = pkg_dir / "coach_input_package_before_ai_judge_input_v0_7_backup.json"
    shutil.copyfile(coach_input_current, backup_path)

    meta = coach_input.setdefault("meta", {})
    meta["version"] = "v0_7"
    meta["last_enriched_by"] = ENRICHER_VERSION
    meta["last_enriched_at_utc"] = datetime.now(timezone.utc).isoformat()

    source_files = coach_input.setdefault("source_files", {})
    ai_sources = source_files.setdefault("ai", {})
    ai_sources["ai_coach_judge_input"] = rel(ai_input_current, root)

    evidence_sections = coach_input.setdefault("evidence_sections", {})
    evidence_sections["ai_coach_judge_input"] = {
        "status": "ok",
        "section_type": "ai_coach_judge_input",
        "summary": {
            "version": ai_input.get("meta", {}).get("version"),
            "round_cards_for_model": len(ai_input.get("round_cards_for_model", [])),
            "top_rounds": [x.get("round_num") for x in ai_input.get("round_cards_for_model", [])],
            "source_contract": ai_input.get("meta", {}).get("source_contract"),
        },
        "model_contract": compact(ai_input.get("model_contract"), limit_list=12, limit_dict_keys=50),
        "match_context": compact(ai_input.get("match_context"), limit_list=12, limit_dict_keys=50),
        "round_cards_for_model_sample": compact(ai_input.get("round_cards_for_model"), limit_list=12, limit_dict_keys=70),
        "final_instruction": ai_input.get("final_instruction"),
    }

    contract_health = coach_input.setdefault("contract_health", {})
    contract_health["ai_coach_judge_input_status"] = "ok"
    contract_health["has_ai_coach_judge_input"] = True
    contract_health["sections_count"] = len(evidence_sections)

    ai_contract = coach_input.setdefault("ai_contract", {})
    tasks = ai_contract.get("judge_tasks_v0_1", [])
    if isinstance(tasks, list):
        has_task = any(isinstance(x, dict) and x.get("task_id") == "ai_coach_judge_generation" for x in tasks)
        if not has_task:
            tasks.append({
                "task_id": "ai_coach_judge_generation",
                "input_sections": ["evidence_sections.ai_coach_judge_input"],
                "output": "final grounded coach review generated by an external/model layer"
            })
        ai_contract["judge_tasks_v0_1"] = tasks

    gaps = ai_contract.get("known_gaps_v0_6", [])
    if isinstance(gaps, list):
        gaps.append(
            "ai_coach_judge_input_v0_1 exists, but no external LLM/API call is executed yet"
        )
        ai_contract["known_gaps_v0_7"] = gaps

    ui_contract = coach_input.setdefault("ui_contract", {})
    order = ui_contract.get("recommended_screen_order", [])
    if isinstance(order, list):
        order = insert_after(order, "evidence_sections.decision_context", "evidence_sections.ai_coach_judge_input")
        ui_contract["recommended_screen_order"] = order

    out_versioned = pkg_dir / f"coach_input_package_{player}_v0_7.json"
    out_current = pkg_dir / "coach_input_package_current.json"

    write_json(out_versioned, coach_input)
    write_json(out_current, coach_input)

    index_path = pkg_dir / f"coach_input_package_index_{player}_v0_7.csv"
    with index_path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=["key", "value"])
        writer.writeheader()
        writer.writerow({"key": "status", "value": "ok"})
        writer.writerow({"key": "match_id", "value": match_id})
        writer.writerow({"key": "player", "value": player})
        writer.writerow({"key": "version", "value": "v0_7"})
        writer.writerow({"key": "enricher", "value": ENRICHER_VERSION})
        writer.writerow({"key": "versioned_package", "value": rel(out_versioned, root)})
        writer.writerow({"key": "current_package", "value": rel(out_current, root)})
        writer.writerow({"key": "ai_input_source", "value": rel(ai_input_current, root)})
        writer.writerow({"key": "sections_count", "value": str(len(evidence_sections))})

    return {
        "status": "ok",
        "enricher": ENRICHER_VERSION,
        "match_id": match_id,
        "player": player,
        "coach_input_version": "v0_7",
        "ai_coach_judge_input": {
            "version": ai_input.get("meta", {}).get("version"),
            "round_cards_for_model": len(ai_input.get("round_cards_for_model", [])),
            "top_rounds": [x.get("round_num") for x in ai_input.get("round_cards_for_model", [])],
        },
        "created": {
            "versioned_package": rel(out_versioned, root),
            "current_package": rel(out_current, root),
            "index": rel(index_path, root),
            "backup": rel(backup_path, root),
        }
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--match-id", default="example_match")
    parser.add_argument("--player", default="Player")
    args = parser.parse_args()

    result = enrich(args)
    print(json.dumps(result, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
